### ISSUE TITLE
Toast list

### ISSUE THREAD

**Issue by tcoulter** [tcoulter/marriage#23]
Tradition:
- Best Man
- Maid of Honor
- Dads

Extras: 
- Amanda
- Chelsea (maybe)
- Lauren (maybe)

**Comment by tcoulter** [comment]
Contact peoples (I'll contact Jeff and my Dad)

**Comment by snmcvay** [comment]
Rehearsal dinner speeches? More family members, more intimacy. Save wedding speeches to limited people.

**Comment by tcoulter** [comment]
Final toast list:
- Lindsey McVay
- Amanda Young
- Kevin Wong
- Connie & Gary Gogel
