### ISSUE TITLE
Dried flowers for aisle

### ISSUE THREAD

**Issue by snmcvay** [tcoulter/marriage#31]
Flowers or leaves? We need to buy them SOON.

**Comment by tcoulter** [comment]
Done! Purchased 100 really well preserved fall maple leaves, in case we need them for some sort of decoration. Then bought 200 very cheap assorted fall leaves and 200 cheaper, less well preserved maple leaves from a different seller. 500 leaves should be enough!

**Comment by tcoulter** [comment]
From the Etsy seller: 

"Currently I am little low on oak and poplar but will be replenishing this week and I will ship yours before the end of the week. You should have them by October 5th. Thank you for your order!"
