### ISSUE TITLE
Processional Music

### ISSUE THREAD

**Issue by tcoulter** [tcoulter/marriage#4]
- Prelude
- Processional for Tim
- Processional for Sarah
- Exit
- Entrance to Reception
- First dance
- Cake cutting
- Exit when we leave

**Comment by tcoulter** [comment]
**Prelude**

Kishi Bashi - "Manchester" (or good for Tim's processional) - https://www.youtube.com/watch?v=Ab495dKtU98

**Processional for Sarah**

Cat Power - "Sea of Love" - https://www.youtube.com/watch?v=CbMeAOTPJzM

**Exit**

Jackson, Timberlake - "Love never felt so good" - https://www.youtube.com/watch?v=oG08ukJPtR8

**First Dance**

Paul McCartney - "Calico Skies" - https://www.youtube.com/watch?v=Bqu1e_Mdhqs

**Comment by tcoulter** [comment]
*Possible Processionals (Tim) or First Dances*

Louis Armstrong - La vie en Rose - https://www.youtube.com/watch?v=qtfJj8oF6xM
MoonGlows - Sincerely - https://www.youtube.com/watch?v=XsxVKN114M0
DNCE - Jinx - https://www.youtube.com/watch?v=I17pbWC8v9E (processional)

**Comment by snmcvay** [comment]
Final:
- **Prelude:** Kishi Bashi - "Manchester" (or good for Tim's processional) -
- **Processional for Tim:** Jinx - DNCE
- **Processional for Sarah:** Calico Skies - Paul McCartney
- **Exit:** Love never felt so good - Jackson
- **Entrance to Reception:** Daryl Hall & John Oates - You Make My Dreams
- **First dance:** Hold me, thrill me, kiss me - She & Him
- **Cake cutting:** Wouldn't it be nice - Beach Boys
- **Exit when we leave:** (I've Had) The Time Of My Life - Bill Medley, Jennifer Warnes
