### ISSUE TITLE
Pie topper

### ISSUE THREAD

**Issue by snmcvay** [tcoulter/marriage#46]

**Comment by tcoulter** [comment]
Possibles: 
- Love birds (cheap) - https://www.walmart.com/ip/Love-Birds-Cake-Topper/46699908
- More birds - http://beforetheidos.com/sweet-tweets-bride-and-groom-cake-topper/?gclid=CjwKEAjw97K_BRCwmNTK26iM-hMSJABrkNtbF5LWagG38P4msybNT50PfkAXZmcynv_IsmpAMLKzKhoCLLbw_wcB
- Kit - https://food52.com/shop/products/1103-diy-wedding-cake-topper-kit?gclid=CjwKEAjw97K_BRCwmNTK26iM-hMSJABrkNtbYl6CRWTYlnnYBQJWljZXpacw9BbR2w9WBbkJdp17oRoCZ0fw_wcB
- Paint your own gnome - https://www.etsy.com/listing/176042740/ready-to-paint-gnome-cake-topper-set-for?utm_source=google&utm_medium=cpc&utm_campaign=shopping_us_d-weddings-decorations-cake_toppers&utm_custom1=4395c8d3-5a03-483d-93a0-37c6c51ae9a0&gclid=CjwKEAjw97K_BRCwmNTK26iM-hMSJABrkNtbukegScaDDrprkql8WIaVjm7aihyzt881c_m-EK39zBoCZKLw_wcB
- Vintage? http://www.ebay.com/itm/like/201666374756?lpid=82&chn=ps&ul_noapp=true
