### ISSUE TITLE
Make Repo Private

### ISSUE THREAD

**Issue by Stoyvo** [tcoulter/marriage#71]
Congrats on the wedding! Clever way of keeping on top of it.

Also, when you search "Marriage" on github - this comes up. Figured it was worth mentioning in an issue?

**Comment by tcoulter** [comment]
Cryptoglance stoyvo! I didn't realize you could submit issues. It's a good point, but part of making it public was keeping it free. I actually just had the conversation with my wife: nothing here is anything we want to keep private, but if we get enough external issues, we might be forced to. :) Great to hear from you!

**Comment by Stoyvo** [comment]
I should have known you already thought of it :P 

Congrats again! Cheers until next time
